const {chromium}=require('playwright');const fs=require('node:fs');
(async()=>{
const browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage']});
const context=await browser.newContext({viewport:{width:430,height:932},hasTouch:true});
let language='ru';const page=await context.newPage();const errors=[];
page.on('console',m=>{console.log(m.type(),m.text());if(m.type()==='error'||/SCRIPT ERROR|ERROR:/.test(m.text()))errors.push(m.text());});
page.on('pageerror',e=>errors.push(e.message));
await page.route('**/sdk.js',route=>route.fulfill({contentType:'application/javascript',body:`window.__events=[];window.__sdkHandlers={};window.YaGames={init:async()=>({environment:{i18n:{lang:'${language}'},app:{id:'test'}},features:{LoadingAPI:{ready:()=>__events.push('ready')},GameplayAPI:{start:()=>__events.push('start'),stop:()=>__events.push('stop')}},on:(key,fn)=>__sdkHandlers[key]=fn})};`}));
await page.goto('http://127.0.0.1:8765');
await page.waitForFunction(()=>window.__events?.includes('ready'),null,{timeout:180000});
await page.waitForTimeout(1500);await page.screenshot({path:'Tests/Yandex/menu.png'});
await page.touchscreen.tap(215,786);
await page.waitForFunction(()=>window.__events?.includes('start'),null,{timeout:120000});
await page.waitForTimeout(1000);await page.screenshot({path:'Tests/Yandex/run.png'});
await page.evaluate(()=>window.__sdkHandlers.game_api_pause());
await page.waitForTimeout(300);
if(!await page.evaluate(()=>window.__events.at(-1)==='stop'))throw Error('Missing stop');
await page.evaluate(()=>window.__sdkHandlers.game_api_resume());
await page.waitForTimeout(500);await page.screenshot({path:'Tests/Yandex/paused.png'});
const result=await page.evaluate(()=>({events:__events,language:DrillDropPlatform.language,save:DrillDropPlatform.readSave(),hidden:DrillDropPlatform.hidden,isolated:crossOriginIsolated}));
if(!result.save)throw Error('Missing saved progress');
if(result.isolated)throw Error('Test must not rely on cross-origin isolation');
const saved=JSON.parse(result.save);
await page.reload();await page.waitForFunction(()=>window.__events?.includes('ready'),null,{timeout:120000});
if(JSON.parse(await page.evaluate(()=>DrillDropPlatform.readSave())).suspended_run.level!==saved.suspended_run.level)throw Error('Save lost after reload');
language='en';await page.reload();await page.waitForFunction(()=>window.__events?.includes('ready'),null,{timeout:120000});
await page.waitForTimeout(500);await page.screenshot({path:'Tests/Yandex/menu-en.png'});
if(await page.evaluate(()=>document.documentElement.lang)!=='en')throw Error('SDK locale not applied');
result.reloadPreserved=true;result.english=true;
fs.writeFileSync('Tests/Yandex/browser.json',JSON.stringify({result,errors},null,2));
console.log(JSON.stringify({events:result.events,errors,saveBytes:result.save.length}));
await browser.close();if(errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
